### ISSUE TITLE
activate fast forward without always keeping the selected key pressed

### ISSUE THREAD

**Issue by GoranXXV** [Hydr8gon/NooDS#100]
Since I'm playing Pokémon HeartGold on my pc, I was wondering if it was possible activating fast forward clicking one time the hotkey without always keeping the selected key pressed🙏

**Comment by Hydr8gon** [comment]
I'll keep this in mind. There are some other hotkeys I've been thinking of adding, so I'll add this to the list as well.

**Comment by Hydr8gon** [comment]
I've implemented this in 938ed0d; you can now map a hotkey for fast forward with either hold or toggle functionality.
