### ISSUE TITLE
compiling error, i need help

### ISSUE THREAD

**Issue by Beginner-codi** [Hydr8gon/NooDS#102]
![2022-04-03_21-18](https://user-images.githubusercontent.com/81601757/161455484-4a519de4-124c-4361-88ad-2bcf90735fa1.png)

**Comment by Hydr8gon** [comment]
The issue is that the current "stable" version of wxWidgets is grossly outdated and doesn't have XDG path support. You'll need to install the latest development version; how to do this depends on your Linux distro. I also need to update the readme to reflect this, heh.

**Comment by Hydr8gon** [comment]
I included a fix in 39c2f5f so older versions of wxWidgets are still supported.
