### ISSUE TITLE
Super Princess Peach lag during transition

### ISSUE THREAD

**Issue by ertaboy356b** [Hydr8gon/NooDS#104]
I'm playing Super Princess Peach but there's a stuttering lag during stage transitions regardless of CPU frequency.

**Comment by Hydr8gon** [comment]
I'm unable to reproduce this. Is it graphical or audio? Could you show a specific example where it happens?

**Comment by ertaboy356b** [comment]
I uploaded a video. https://youtube.com/shorts/-_x8mG_yc-k?feature=share
Wait till peach dies, there will be a stuttering lag. It also happens when you go inside a pipe. While loading a new area, the game will stutter.
