### ISSUE TITLE
Issue regarding, sound

### ISSUE THREAD

**Issue by FrostKnight** [Hydr8gon/NooDS#115]
I get these errors upon starting it, almost every time...
I do make -j4, then make install and this:

ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_sndio.c:383:(sndio_open) sndio: only playback streams are supported
ALSA lib pcm_sndio.c:383:(sndio_open) sndio: only playback streams are supported

I also tried just make install, same thing and flatpak isn't exactly my ideal way of doing this.

Just basic source code building is usually my way of doing things, anywho as you may notice, I am using sndio.

Albeit, alsa-sndio + sndio

As an aside, I absolutely love how few dependencies it requires.

The only things I don't see, are mostly pretty minor, such as, action replay cheat options,
load/save state options, not a huge deal.  sound level control, same. 

I just would like to be able to use my sound as is. 
 :)
That being said, on sndio, there are other ways to control the mixer.

Btw, as an aside, I hope you will keep the dependencies as minimal as possible. I treasure this, given all the bloatware I see being manipulated into linux or as some call it GNU/Linux.

For someone who just started this project to learn about emulators, your work is 1000x better than desmume and still better than melonDS, regarding the size and possibly more.

**Comment by Hydr8gon** [comment]
Does the audio still work despite the errors? I get a bunch of similar messages too, but it still works fine. I don't think there's anything I can do about it since it's a PortAudio thing.

**Comment by FrostKnight** [comment]
> Does the audio still work despite the errors? I get a bunch of similar messages too, but it still works fine. I don't think there's anything I can do about it since it's a PortAudio thing.

The only thing then I want, I guess? Is if you could tell me what I need to do, dosbox-x, desmume, mgba, etc... all work with this setup.

I'' get back to you later, on this... its too late where I am, so peace...

**Comment by FrostKnight** [comment]
Quick update, if I close NooDS, afterwards, I get this error as well:

ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_sndio.c:383:(sndio_open) sndio: only playback streams are supported
ALSA lib pcm_sndio.c:383:(sndio_open) sndio: only playback streams are supported
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840

This is when I use the aur version, in particular.

**Comment by Hydr8gon** [comment]
I don't really know much about audio drivers, unfortunately. I just let PortAudio handle it, so any issues are related to the library or the drivers.

**Comment by FrostKnight** [comment]
> I don't really know much about audio drivers, unfortunately. I just let PortAudio handle it, so any issues are related to the library or the drivers.

Hmm.. perhaps an upstream issue or sndio issue? Idk... but could be closed for now unless a solution is available.

Thanks for trying though.

**Comment by FrostKnight** [comment]
Final update needs to be made, it seems it does work with sndio!  There is just one small issue, but its not on your end at all!
Someone, removed the sndio fix and that resulted in me having an issue.
point being, no worries! 
:) 
Thanks for making one of the most lean emulators out there for nintendo DS. Btw, I hope you will keep gtk as an option for a while... especially gtk2.

:)
You have the only nintendo DS emu that is worth its salt. :)

Aka, portaudio needs a sndio patch which was removed by a dev I know, for some reason?!? Anywho, no worries all! It works well now! :)
