### ISSUE TITLE
Feature Request - BugTrap

### ISSUE THREAD

**Issue by Felipefpl** [Hydr8gon/NooDS#132]
The crash logger of windows is unreliable or can't be done after Dr. Watson ceased to exist after WinXP, even more if you disable the pagefile to optimize the system, that's why i'd like to suggest to add BugTrap on NooDS:

https://github.com/bchavez/BugTrap

Unlike it says on its page it can be used with other code than .NET. It also creates crashlogs with stack dumps already compressed in a .zip file for convenience.

A crash logger such as this would be REALLY useful to find the source of crashes so that's why i suggested to you, i hope you take a look at it and if you like it, add it to NooDS, everybody wins with that. :+1:

**Comment by Hydr8gon** [comment]
To be honest, I don't really want to pull in a whole debugger, especially one specifically for Windows. I use `gdb` to find crashes on Linux, which should also work with MSYS2 on Windows.

**Comment by Felipefpl** [comment]
I see, well, i had to try. :P - at least the idea is here. :)
