### ISSUE TITLE
[Question] Are you considering implementing multiplayer support?

### ISSUE THREAD

**Issue by suchipi** [Hydr8gon/NooDS#135]
This emulator has some really nice features! The screen layout options in particular are really nice (I'm using the Linux version).

I noticed that you can emulate more than once device at once via the "add system" button, so I was curious if you had implemented ad-hoc multiplayer, but it doesn't seem to work (the devices can't see each other). Is that something you're interested in implementing in the future?

Or maybe I just need BIOS dumps from devices with different MAC addresses?

**Comment by Hydr8gon** [comment]
It's something I was working on, but it's very unfinished. Some games are able to detect open lobbies, but joining will definitely fail. The emulator changes the MAC address of each instance, so you don't have to worry about that. I'll probably come back to this at some point, but I'm not actively working on it at the moment.

**Comment by suchipi** [comment]
Thanks for the answer ^^
