### ISSUE TITLE
Suggestion:  Cheats support

### ISSUE THREAD

**Issue by FrostKnight** [Hydr8gon/NooDS#137]
This and save/load states are the only things that this project needs in my opinion for it to be as good as I want it to be.
Would love to have action replay cheats be an option. No huge hurry on this, save/load states to me are more important and you are doing this for fun anyways. 

Just a suggestion from a fan!

Should probably edit this, action replay cheats working like they do in nintendo ds is what I meant.   Just so you know.

**Comment by surlup** [comment]
I agree with this feature
