### ISSUE TITLE
File-less direct launch for Vita

### ISSUE THREAD

**Issue by BlackSheepBoy69** [Hydr8gon/NooDS#138]
Hi! Thanks for all your work on this app. I'd like to ask if you would be willing to stop using args.txt for direct launch in favor of param launches. Normally args.txt is fine but it's just this would be a lot cleaner: no more editting/reading/deleting files and such.

There is a much cleaner way for Vita to do direct launch using a URI call. The emulators 'RetroArch', 'DaedalusX64', 'Flycast', and 'fake-08' launch like this with a URI call:

    function launch_retroarch(romfile, def_core_name)
	System.executeUri("psgm:play?titleid=RETROVITA" .. "&param=" .. def_core_name .. "&param2=" .. romfile)
	System.exit()
    end

    function launch_DaedalusX64(romfile)
	System.executeUri("psgm:play?titleid=DEDALOX64" .. "&param=" .. romfile)
	System.exit()
    end

    function launch_Flycast(romfile)
	System.executeUri("psgm:play?titleid=FLYCASTDC" .. "&param=" .. romfile)
	System.exit()
    end

    function launch_Fake08(romfile)
	System.executeUri("psgm:play?titleid=FAKE00008" .. "&param=" .. romfile)
	System.exit()
    end

The above code is LUA+ code like you'd find in RetroFlow, just to show how simple it is code-wise to **launch** into the other emulators, including fake-08

Here is how they implemented **reading** these URI calls in fake-08, a different emulator also written in C++ that started supporting direct launch like a year ago.
https://github.com/search?q=repo%3Ajtothebell%2Ffake-08+param&type=code
![image](https://github.com/Hydr8gon/NooDS/assets/97395721/098537ea-08dc-4bd2-9071-5cd3bb3d3055)

As I said, if this is added it will remove the hassle of editting/reading/deleting the args.txt file to make direct launch work AND you won't have to worry about a loose args.txt file lying around causing an accidental launch direct into a game: With a URI call there will be no files lying around anymore so no accidental launches direct into a game: it would be a lot cleaner.

As usual, thank you so much for all your work on NooDS and I appreciate so much that you support the relatively unknown platform of Vita. I use it all the time to play the sudoku section in Brain Age 1/2 - it is by far the best sudoku software I've found and I'm very happy that NooDS runs the sudokus as a good speed because of all the optimization you have done so far and thank you!

No public launchers currently rely on args.txt as far as I know. Only experimental ones. As such, you can safely drop support for args.txt completely on Vita if this is added. The only concern might be that args.txt is easier for you to test since you don't need anything else installed on your vita to have an args.txt file. If you reply with the full path of a nintendo DS game, I can make you a vpk for that game so you can direct-launch it from your Vita home menu for testing. I would be more than willing to make 2 if you'd like 1 for GBA and 1 for NDS, for example.

**Comment by Hydr8gon** [comment]
I don't use any app launchers, so I hope that works. The file never felt like a great solution to me, so I'm glad there's a cleaner way to do it.

**Comment by BlackSheepBoy69** [comment]
Works great!!! Here is the LUA+ code I used. So much cleaner now instead of having to mess with a file, thanks!

    function launch_NooDS(romfile)
	System.executeUri("psgm:play?titleid=NOODSVITA" .. "&param=" .. romfile)
	System.exit()
    end
