### ISSUE TITLE
Logger missing

### ISSUE THREAD

**Issue by master1274** [Hydr8gon/NooDS#139]
Shield Tablet 32GB/LTE, Tegra K-1, Android 7.0, ARMv7, 320 dpi(1920х1200), OpenGL ES 3.2, Vulkan 1.0, Core 4x ARM Cortex-A15 - 2218 MHz.
I decided to test GBA emulation. Starts at good speed. But it crashes after some time. There are no root rights on the device. There is also no PC for using ADB. The absence of a logger in the emulator does not contribute to its development. Because in my case there is no way to help other than simply report the problem.

**Comment by master1274** [comment]
The situation has not changed. Stable crashes a few seconds after starting any GBA game.

**Comment by Hydr8gon** [comment]
There's unfortunately not much I can do without a logcat to see the cause of the crash. The concept of adding a "logger" is pretty vague; I have print-based logs that I can enable on desktop, but they won't help with a device-specific crash. I've tested various other devices and can't reproduce the issue.

**Comment by master1274** [comment]
To our mutual regret, I do not have root access. And no PC. Therefore, I will not be able to provide the log. The only thing I can provide is some information about the device. I'm not sure if this will help solve the problem. The problem is very similar in description to https://github.com/Hydr8gon/NooDS/issues/140
It's a pity that I can't help in identifying the problem. 
[Shield Tablet Info.txt](https://github.com/Hydr8gon/NooDS/files/13222820/Shield.Tablet.Info.txt)

**Comment by Hydr8gon** [comment]
I might have fixed this in the latest build; see discussion on the other issue. Let me know if it's fixed for you.

**Comment by master1274** [comment]
Yes. In the latest build the crash has been fixed for my device. Thank you.
