### ISSUE TITLE
Crash after some time

### ISSUE THREAD

**Issue by Sohil876** [Hydr8gon/NooDS#140]
Crashes after some time (like 10 to 20 seconds) on all gba games i've tried.

OS: Android (10)
Arch: armv8l

Here is the [Logcat of crash](https://nekobin.com/pofepafuzu.txt)

**Comment by Hydr8gon** [comment]
The logcat link doesn't work for me. Could you try uploading it again?

**Comment by Sohil876** [comment]
> The logcat link doesn't work for me. Could you try uploading it again?

It was expired maybe, here:
https://nekobin.com/belilewasu

**Comment by Hydr8gon** [comment]
I might've been too late because it's still not working. Would you be able to put the log in a text file and attach that here?

**Comment by Sohil876** [comment]
> I might've been too late because it's still not working. Would you be able to put the log in a text file and attach that here?

[logcat_10-21-2023_18-04-50.txt](https://github.com/Hydr8gon/NooDS/files/13236369/logcat_10-21-2023_18-04-50.txt)

**Comment by Hydr8gon** [comment]
Turns out I've had a device that triggers this crash all along. I tracked it down to a division by zero that happens when touching the screen outside of buttons in GBA mode. Let me know if it's fixed for you in the latest build with 830983d.

**Comment by Sohil876** [comment]
> Turns out I've had a device that triggers this crash all along. I tracked it down to a division by zero that happens when touching the screen outside of buttons in GBA mode. Let me know if it's fixed for you in the latest build with 830983d.

Yes no longer crashes.
