### ISSUE TITLE
Request to add Wii as a target build platform 

### ISSUE THREAD

**Issue by radicalten** [Hydr8gon/NooDS#150]
Hello, 

Is it possible to port NooDS to the Wii (2006) platform? 

I believe porting this project to the Wii would align with your two goals: "I started working on NooDS for fun and as a learning experience, and I'd like to keep it that way. If people are interested and get use out of it, that's a bonus!" 

For the 1st goal: there is a lot to learn about Wii development (which can be fun). And for the 2nd goal: there is certainly interest in a Wii DS emulator as the pointer control interface of the wii remote (or gyro of the WiiMotionPlus) is a good match for the DS stylus. 

Thank you for creating and maintaining this project!

--
p.s. 
It may be helpful to know that development of a DS emulator for Wii started in 2010, but stopped in 2013. The developers were able to accomplish full speed emulation of certain 2D games like Yoshi's Island DS, however most 3D games would crash on system startup. I have linked the latest branch of that project here. Hopefully you will find this resource useful. 

https://github.com/scanff/desmumewii/tree/GCC-Update
Description: "This project aims to port DeSmuME to Wii homebrew so that we can have a fully fledged, working, Nintendo DS emulator on Wii. It is being built with DeSmuME 0.95 and the latest available devkitPPC and libogc releases"

**Comment by Hydr8gon** [comment]
NooDS would run very poorly on the Wii right now. Even the Wii U barely reaches full speed in anything, and the Wii is a significant downgrade from that. It doesn't even have multiple cores, which is where a decent chunk of NooDS' performance comes from. That's not to say it won't ever happen, but for now I don't really want to support another platform that runs horribly :sweat_smile:

**Comment by radicalten** [comment]
Thanks for your consideration 👍

**Comment by radicalten** [comment]
Hello Mr. Hydr8gon, 

I wanted to inform you that I eventually did create a (WIP) port of NooDS to the Wii.

As you stated, it currently has low fps, nevertheless it is an interesting project. 

Thanks,

<img width="1458" height="1012" alt="Image" src="https://github.com/user-attachments/assets/0166ce45-b343-4a85-b079-413e49862e8e" />
