### ISSUE TITLE
Request   fix crash for vita3K(PSVITA Emulation)

### ISSUE THREAD

**Issue by surlup** [Hydr8gon/NooDS#154]
for Vita3K emulation crash after click into the game you can see the logs 
[NOODSVITA - [NooDS].log](https://github.com/user-attachments/files/16184636/NOODSVITA.-.NooDS.log)
![image](https://github.com/user-attachments/assets/478d8ada-8cad-4269-b24c-17951a515cec)
Hope you can fix this [Hydr8gon](https://github.com/Hydr8gon)

**Comment by Hydr8gon** [comment]
It works on hardware, so I would say this is a bug on Vita3K's end.

**Comment by surlup** [comment]
Ok
