### ISSUE TITLE
Homie Rollerz (USA) (En,Es) missing racer and glitchy track

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#23]
on the top screen it is missing the racer
and during the race the track keeps flashing and disappearing
![homie](https://user-images.githubusercontent.com/2696404/84474004-a75de880-acbc-11ea-9cd6-8559ca2bdb18.PNG)

**Comment by Arisotura** [comment]
that game sets a fucked-up viewport; you'll need to emulate the exact viewport-transform formula (under specific circumstances the calculations overflow and wrap around)

**Comment by Hydr8gon** [comment]
The missing racer should be fixed by ba2636f, but the flashing track sounds like a separate issue. Probably something related to the GXFIFO.
