### ISSUE TITLE
Legend of Spyro, The - The Eternal Night (USA) missing text

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#26]
![spyro](https://user-images.githubusercontent.com/2696404/84477183-d32f9d00-acc1-11ea-892d-8b2b4697eb7d.PNG)

**Comment by Hydr8gon** [comment]
Looks like this is 3D, so it's probably some sort of depth issue.

**Comment by Hydr8gon** [comment]
I guess this was actually a VRAM mirroring issue; it was fixed by e541c06.
