### ISSUE TITLE
Micro Machines V4 (Europe) corrupt graphics

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#32]
your car is glitchy 
the start line flags are glitchy aswell
![micro](https://user-images.githubusercontent.com/2696404/84481067-1856cd80-acc8-11ea-82bf-757dbcb3b4e4.PNG)
![micro1](https://user-images.githubusercontent.com/2696404/84481112-2e648e00-acc8-11ea-9e88-975f23ea9ace.PNG)

**Comment by Hydr8gon** [comment]
Looks like this is fixed by b49fb0a as well, yay!
