### ISSUE TITLE
Colour Cross (Europe) missing grid

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#34]
![cross](https://user-images.githubusercontent.com/2696404/84481834-4b4d9100-acc9-11ea-8c26-9d14f797b922.PNG)

**Comment by Hydr8gon** [comment]
Apparently this game uses the 3D engine for rendering. From GBATEK:
`Line Segments are rendered always because they do not have any front and back sides.`
I assume this is the problem, because I know I'm not currently handling line segments properly.

**Comment by Hydr8gon** [comment]
Oh, it could also be using wireframe polygons. In fact, that's probably what it's using. I need to handle those too.
