### ISSUE TITLE
Madden NFL 09 (USA) all players have black uniforms

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#36]
both teams look the same

**Comment by Hydr8gon** [comment]
Are they entirely black (totally missing textures) or do the numbers still show up? Do you have a screenshot?

**Comment by Hydr8gon** [comment]
I wonder if this is also a texture coordinate transformation issue. Could you retest with the latest build?

**Comment by Hydr8gon** [comment]
Nevermind, the problem seems to be incorrect highlight shading. The formula on GBATEK is wrong; the correct formula can be found [here](http://melonds.kuribo64.net/board/thread.php?id=13).
