### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by binocry** [Hydr8gon/NooDS#39]
so in readme say you can can download using automatic builds via GitHub Actions, but i try download windows version always corrupted?

**Comment by Hydr8gon** [comment]
Corrupted how? I just tried downloading the latest Windows build and it seems to be fine.

**Comment by binocry** [comment]
> 
> 
> Corrupted how? I just tried downloading the latest Windows build and it seems to be fine.

Never mind, it's fine now. Yesterday when i download android or windows version always download 1.2mb file and can't be opened.
i will close this issue
