### ISSUE TITLE
[Suggestion] Rename math.h

### ISSUE THREAD

**Issue by raphasanori** [Hydr8gon/NooDS#40]
Although good compilers  and well-configured build systems can make this an impossible problem, old build systems and compilers and weird situations can cause conflicts with the standard library header with the same name.

Work needed?
rename math.h and math.cpp
rename the include in math.cpp and core.h

**Comment by Hydr8gon** [comment]
Good point; I'll have to think of a better name (division? divsqrt? nds_math?).

**Comment by raphasanori** [comment]
I think divsqrt, ds_math or nds_math should work!? I would vote to nds_math.

**Comment by Hydr8gon** [comment]
I ended up going with div_sqrt, just because nds_math felt a little weird (nothing else has an nds_ prefix).
