### ISSUE TITLE
Please rename

### ISSUE THREAD

**Issue by eeveelution1313** [Hydr8gon/NooDS#41]
Please rename from NooDS to NuuDS plz

**Comment by nadiaholmquist** [comment]
no u

**Comment by JosefineJensen** [comment]
plz

**Comment by Hydr8gon** [comment]
you're a derp

**Comment by Arisotura** [comment]
pls rename NooDS to melonDS

**Comment by Hydr8gon** [comment]
This is a derpy issue

**Comment by Arisotura** [comment]
pls rename eeveelution1313 to eeveelution1312

**Comment by eeveelution1313** [comment]
plz rename

**Comment by eeveelution1313** [comment]
my girlfriend just made me delete my entire user profile, this is the least you can do for me <3

**Comment by nadiaholmquist** [comment]
tffp
