### ISSUE TITLE
[Feature Request] Pin android storage directory 

### ISSUE THREAD

**Issue by Gamemulatorer** [Hydr8gon/NooDS#47]
Everytime I open the NooDS I always need to locate the storage directory of my nds roms can you add an option to pin it?
![Screenshot_2021-06-12-13-22-43-210_com hydra noods](https://user-images.githubusercontent.com/37603562/121766042-e3eb4b00-cb81-11eb-8421-2cbacf2e1527.jpg)

Sorry for my English hope you understand me :)
Goodluck and God Bless to this emulator 🙏

My android phone is redmi note 9 android 10

**Comment by Gamemulatorer** [comment]
Offtopic
@Hydr8gon can you possibly add an option like this in NooDS?
![IMG_20230219_103636](https://user-images.githubusercontent.com/37603562/219909120-5b4ff859-ebaf-4076-9bf3-63baf4a2ec48.jpg)

**Comment by Hydr8gon** [comment]
I'm not really sure what that means. It seems to be an option from a PS2 emulator, but the post describing it doesn't exist anymore. It's also not related to this issue; feel free to open a new one if you have more information.

**Comment by Gamemulatorer** [comment]
Closing this because storage directory is working.
