### ISSUE TITLE
Save State Support

### ISSUE THREAD

**Issue by mrdeathjr28** [Hydr8gon/NooDS#5]
Hi

save state support will be nice

And thanks for your work

**Comment by Hydr8gon** [comment]
It'll happen eventually, but right now I'm hesitant to implement them because the core is still unfinished and likely to undergo significant changes. Basically, I don't want to break save state compatability every time I update the code.

**Comment by FrostKnight** [comment]
> It'll happen eventually, but right now I'm hesitant to implement them because the core is still unfinished and likely to undergo significant changes. Basically, I don't want to break save state compatability every time I update the code.

Is this still true? Would love to have save/load states as an option. :)

control-x with x being any number 1 through 9 and possibly zero as well. 

This being said, your emulator looks good so far. I like, no, LOVE, how its way more lightweight, K.I.S.S friendly.

As previously stated, even if you made it rolling release, its still 1000% better than other emulators of the same kind.
