### ISSUE TITLE
New Super Mario Bros. "Non Bootable"

### ISSUE THREAD

**Issue by joyful-cambion** [Hydr8gon/NooDS#51]
Hello, 
So I've tried New Super Mario Bros. DS on the emulator but it doesn't work, I just get this message 
![Screenshot_20210625-142447](https://user-images.githubusercontent.com/74503778/123432809-ab586200-d5c2-11eb-8f9b-762d45e24f8a.jpg)

It looks that the game doesn't recognize the Game Card, although I tried changing save type but without any success

**Comment by Hydr8gon** [comment]
It should work with a save type of EEPROM 64KB.
![image](https://user-images.githubusercontent.com/3057954/123472544-4c481c80-d5c5-11eb-9ea8-8ae40148f6c4.png)

**Comment by joyful-cambion** [comment]
thanks much it worked :)
