### ISSUE TITLE
NooDS android doesn't recognize external storage

### ISSUE THREAD

**Issue by 1onLSD** [Hydr8gon/NooDS#52]
Hello, 
So I found that it's impossible to navigate to external storage with NooDS on Android, there is no option to change storage type or navigate to root directory
--
![Screenshot_20210710-143324](https://user-images.githubusercontent.com/74503778/125164772-cebb0980-e18b-11eb-9d57-a9e4c5d86768.jpg)

**Comment by Hydr8gon** [comment]
Sorry it took so long; this should be fixed by e9e39b4. I haven't been able to test on an actual device, but it seems to work on the Android emulator.
