### ISSUE TITLE
make with fatal error: 'portaudio.h' file not found, but  I've installed this

### ISSUE THREAD

**Issue by lluvio** [Hydr8gon/NooDS#54]
![image](https://user-images.githubusercontent.com/6127266/126191725-7a08afd6-3f09-45c9-b20c-0cc5d0e8512d.png)

**Comment by Hydr8gon** [comment]
Hmm, that's strange. What macOS version are you on? Worst case, you can get a macOS build from the [releases page](https://github.com/Hydr8gon/NooDS/releases). I don't have a Mac myself, so I'm not sure how much help I can be here :/

**Comment by lluvio** [comment]
No problem. @Hydr8gon 

I just want to try to build a native with apple silicon. It doesn't matter if the build fails. I could play NooDS with Rosetta

**Comment by Hydr8gon** [comment]
Hey! Bit of a late update on this, but 290ff4a should fix the issue.
