### ISSUE TITLE
thanks for the amazing work, it's a request to be able to run the DS system on ps Vita like adrenaline, and I'm also suggesting creating a plugin to use DS screens better on ps Vita.

### ISSUE THREAD

**Issue by Sal-gamer** [Hydr8gon/NooDS#66]
I loved being able to run the Nintendo DS system on ps Vita, could you improve the use of the Nintendo DS system to look like adrenaline?  thank you so much for this amazing work, right in the first versions it's at 10 FPS, I felt the image sharper in the last update too, I'm looking forward to more update, and hope to be able to run the DS system on my PS Vita one day, I tried put the date of my birth and change the colors of the Nintendo DS but it doesn't save, I wanted to be able to customize and have this experience, one more thing, Xerpi created a udcvudc plugin for PS Vita that allows recording the PS Vita screen on the PC itself at 1280x720 you would be able to get the code for this plugin and modify it so the top DS screen is the USB streaming screen on the PC, and on the ps Vita the screen could you use it as the bottom screen enabling toutch?  or for those who prefer to transmit the lower screen, put the lower one on the USB transmission and on the ps Vita the upper screen but with toutch responding to the lower screen on the PS Vita?  if it's too much work can you at least try talking to Xerpi?  Could you try making a plugin for your Nintendo DS Vita emulator?  Thanks in advance.

[Adrenaline Vita ](https://github.com/TheOfficialFloW/Adrenaline) 

[Udcvudc plugin]
(https://github.com/xerpi/vita-udcd-uvc)

**Comment by Hydr8gon** [comment]
It feels a bit out of scope for this project to have a custom udcd-uvc implementation, and it's not something I'm really interested in doing. The Vita is probably too weak to ever run most DS games full speed anyway, so if you're already in front of a computer you'd be better off emulating it on there directly. You can probably find something to stream your computer screen to your Vita and achieve effectively the same setup.

**Comment by Sal-gamer** [comment]
A modified udcvudc implementation would be awesome to use DS on ps Vita , PS Vita and a quad-core with 500mhz currently with homebrew and emulators can use this fourth core easily and also Vita is with VitaGL which converts the openGL library to PS Vita, and it has the PowerVR library that was ported to PS Vita, it has 512 RAM 128 vram is an ARM processor like DS, I think it would run fine, it depends on how good a programmer the person is, and their experience, the adrenaline runs super well , PSP and much heavier to emulate than DS , they already managed using Java script emulate ps1 by browser using ROM installed on PC , it is playing very fluid , and many said it was not possible since Java is difficult to work being heavy for emulation, a good developer came and ported, Bully, GTA vice city from PS Vita were ports that many considered impossible, now rinnegataly want to go to another level is to port doom 3 to PS Vita, I think you're working  on many platforms at the same time this is what makes all platforms suffer from the lack of focus and individual objective, a person working on 1 project for a platform, has more income and improvements in emulation compared to doing for several and both do not have one Very high performance, the Vita community is huge full of fans passionate about the console, yes I can play Nintendo DS on my cell phone it's PC without problems but that's not the point, I want to play on ps Vita without transmitting the PC screen to it, and I'd like of being able to play a screen in ps Vita another in udcvudc but if there is no way , fine , I just ask for a good emulator that runs well , pay more attention to PS Vita since emulation is the worst of all , the Vita community and big , why not do something separate and stay in it ?  The community can support you in this, please pay more attention to ps Vita, there are several channels supporting and spreading the word that you are creating a DS emulator for PS Vita, and everyone with hope and believing in your project, channels with more than 5,000 subscribers making video about ds Vita , several twitter , forum , blog , thousands of people excited about the idea of ​​a DS Vita , I just made a request to put a udcvudc modification but if you can not ok , but damn if you think it will be difficult to do games run 100% on ps Vita, if you think you won't even run some games 100% face this challenge, roll up your sleeves and do your best to create the best is fastest DS emulator that Vita can have, don't If you leave it for granted, do you think that in the creation of The game doom the team is the programmers simply said I think this game won't run 100% fast as we wanted, won't it be as fast as the games that exist on the market?  Do you think the team said that the 3d effect wouldn't be 100% so it wouldn't have a good 3d illusion?  No, it is not!  They made one of the fastest and most frantic games of their time, they made a 3d game in a time that didn't have hardware for 3d games on console, they went overboard the industry is full of talented programmers who didn't let themselves down just because seemed difficult, ports of Android games to PS Vita seemed impossible The flow created a way to get the Lib file that uses the ARM processor to boot the game, and with that change some triggers and paths to run Android games on ps Vita 2 years ago they would say it's impossible to do that, they're working on a Nintendo 64 emulator for the PS Vita and it already runs a lot of games well and it's Nintendo 64 an extremely difficult emulator to work with, they took a break to work on a port for the PS Vita, I think if you work on ps Vita separately and dedicate yourself to it it would run DS games well.

**Comment by Sal-gamer** [comment]
A modified udcvudc implementation would be awesome to use DS on ps Vita , PS Vita and a quad-core with 500mhz currently with homebrew and emulators can use this fourth core easily and also Vita is with VitaGL which converts the openGL library to PS Vita, and it has the PowerVR library that was ported to PS Vita, it has 512 RAM 128 vram is an ARM processor like DS, I think it would run fine, it depends on how good a programmer the person is, and their experience, the adrenaline runs super well , PSP and much heavier to emulate than DS , they already managed using Java script emulate ps1 by browser using ROM installed on PC , it is playing very fluid , and many said it was not possible since Java is difficult to work being heavy for emulation, a good developer came and ported, Bully, GTA vice city from PS Vita were ports that many considered impossible, now rinnegataly want to go to another level is to port doom 3 to PS Vita, I think you're working  on many platforms at the same time this is what makes all platforms suffer from the lack of focus and individual objective, a person working on 1 project for a platform, has more income and improvements in emulation compared to doing for several and both do not have one Very high performance, the Vita community is huge full of fans passionate about the console, yes I can play Nintendo DS on my cell phone it's PC without problems but that's not the point, I want to play on ps Vita without transmitting the PC screen to it, and I'd like of being able to play a screen in ps Vita another in udcvudc but if there is no way , fine , I just ask for a good emulator that runs well , pay more attention to PS Vita since emulation is the worst of all , the Vita community and big , why not do something separate and stay in it ?  The community can support you in this, please pay more attention to ps Vita, there are several channels supporting and spreading the word that you are creating a DS emulator for PS Vita, and everyone with hope and believing in your project, channels with more than 5,000 subscribers making video about ds Vita , several twitter , forum , blog , thousands of people excited about the idea of ​​a DS Vita , I just made a request to put a udcvudc modification but if you can not ok , but damn if you think it will be difficult to do games run 100% on ps Vita, if you think you won't even run some games 100% face this challenge, roll up your sleeves and do your best to create the best is fastest DS emulator that Vita can have, don't If you leave it for granted, do you think that in the creation of The game doom the team is the programmers simply said I think this game won't run 100% fast as we wanted, won't it be as fast as the games that exist on the market?  Do you think the team said that the 3d effect wouldn't be 100% so it wouldn't have a good 3d illusion?  No, it is not!  They made one of the fastest and most frantic games of their time, they made a 3d game in a time that didn't have hardware for 3d games on console, they went overboard the industry is full of talented programmers who didn't let themselves down just because seemed difficult, ports of Android games to PS Vita seemed impossible The flow created a way to get the Lib file that uses the ARM processor to boot the game, and with that change some triggers and paths to run Android games on ps Vita 2 years ago they would say it's impossible to do that, they're working on a Nintendo 64 emulator for the PS Vita and it already runs a lot of games well and it's Nintendo 64 an extremely difficult emulator to work with, they took a break to work on a port for the PS Vita, I think if you work on ps Vita separately and dedicate yourself to it it would run DS games well.

**Comment by Sal-gamer** [comment]
A modified udcvudc implementation would be awesome to use DS on ps Vita , PS Vita and a quad-core with 500mhz currently with homebrew and emulators can use this fourth core easily and also Vita is with VitaGL which converts the openGL library to PS Vita, and it has the PowerVR library that was ported to PS Vita, it has 512 RAM 128 vram is an ARM processor like DS, I think it would run fine, it depends on how good a programmer the person is, and their experience, the adrenaline runs super well , PSP and much heavier to emulate than DS , they already managed using Java script emulate ps1 by browser using ROM installed on PC , it is playing very fluid , and many said it was not possible since Java is difficult to work being heavy for emulation, a good developer came and ported, Bully, GTA vice city from PS Vita were ports that many considered impossible, now rinnegataly want to go to another level is to port doom 3 to PS Vita, I think you're working  on many platforms at the same time this is what makes all platforms suffer from the lack of focus and individual objective, a person working on 1 project for a platform, has more income and improvements in emulation compared to doing for several and both do not have one Very high performance, the Vita community is huge full of fans passionate about the console, yes I can play Nintendo DS on my cell phone it's PC without problems but that's not the point, I want to play on ps Vita without transmitting the PC screen to it, and I'd like of being able to play a screen in ps Vita another in udcvudc but if there is no way , fine , I just ask for a good emulator that runs well , pay more attention to PS Vita since emulation is the worst of all , the Vita community and big , why not do something separate and stay in it ?  The community can support you in this, please pay more attention to ps Vita, there are several channels supporting and spreading the word that you are creating a DS emulator for PS Vita, and everyone with hope and believing in your project, channels with more than 5,000 subscribers making video about ds Vita , several twitter , forum , blog , thousands of people excited about the idea of ​​a DS Vita , I just made a request to put a udcvudc modification but if you can not ok , but damn if you think it will be difficult to do games run 100% on ps Vita, if you think you won't even run some games 100% face this challenge, roll up your sleeves and do your best to create the best is fastest DS emulator that Vita can have, don't If you leave it for granted, do you think that in the creation of The game doom the team is the programmers simply said I think this game won't run 100% fast as we wanted, won't it be as fast as the games that exist on the market?  Do you think the team said that the 3d effect wouldn't be 100% so it wouldn't have a good 3d illusion?  No, it is not!  They made one of the fastest and most frantic games of their time, they made a 3d game in a time that didn't have hardware for 3d games on console, they went overboard the industry is full of talented programmers who didn't let themselves down just because seemed difficult, ports of Android games to PS Vita seemed impossible The flow created a way to get the Lib file that uses the ARM processor to boot the game, and with that change some triggers and paths to run Android games on ps Vita 2 years ago they would say it's impossible to do that, they're working on a Nintendo 64 emulator for the PS Vita and it already runs a lot of games well and it's Nintendo 64 an extremely difficult emulator to work with, they took a break to work on a port for the PS Vita, I think if you work on ps Vita separately and dedicate yourself to it it would run DS games well.

**Comment by Hydr8gon** [comment]
The DS in particular is a demanding console to emulate. It has two CPUs with slightly different architectures, two 2D engines that have to be emulated in software, and a 3D engine that doesn't map well to modern GPUs. It's also difficult to multithread a lot of things because you need tight synchronization, so the majority of the work has to be done on a single thread.

The Vita has a dedicated CPU for running PSP games, so that's not entirely emulation. For something like the N64, heavy use of HLE and the ability to render everything with hardware makes it much easier to achieve good performance on lower-end devices. I'm not saying it's impossible, but... there's a reason a fast DS emulator for the Vita hasn't shown up yet.

That's not to say I won't try. A JIT recompiler would certainly help achieve better speeds on the Vita, and I'm always working on additional optimizations. The reason I keep telling people that it's unlikely we'll see full speed DS emulation is because I don't want anyone to get their hopes up in the case that it doesn't happen.

**Comment by Sal-gamer** [comment]
I understand that it's not easy is that it's quite a challenge, but PS Vita has 4 cores that can be used in homebrew if the developer activates this option in their emulator, I know they are liberally different cpus and 3ds also does that, but I believe that a good emulation is possible, with a little effort, The flow is working so that the psp's dedicated CPU is used for emulators, would that help you?  about why no one works on the PS Vita DS is why it's not easy to emulate DS I understand but above all and why there's someone interested in making the emulator, it's not because it would be impossible to run 100%, it's because it needs to of well qualified people like you , do you think why before rinnegatamente is the do flow had no Nintendo 64 emulator on Vita ?  because it is difficult to work on emulation of 64bits and Nintendo 64 itself , but it got to be done , paused because of PS Vita ports but it has a list of 100% playable games already , it is not true that it does not have another person working on DS for PS Vita , there's one more sign besides you working on a new DS emulator for PS Vita , can you tell me more about this JIT recompiler?

**Comment by Sal-gamer** [comment]
![legend (1)](https://user-images.githubusercontent.com/55700359/135361411-852424d4-83cc-427a-8432-9b4ade6f62e0.png)
Look at this screenshot of a possible DS emulator development for PS Vita, the official cuevavirus developer photo

**Comment by Sal-gamer** [comment]
Thanks for all the support, sorry for any inconvenience and I'll be looking forward to the next updates as I love Vita as you do and look forward to what's yet to come.

**Comment by vsmgammer** [comment]
Ola amigo estou acompanhando seu magnifico projeto Ds no vita e como o amigo citou acima eu sou um dos que fiz video pro meu canal a respeito e deu um hype bacana o pessoal esta muito empolgado e esperançoso neste emulador ja que ate agora vc é o unico trabalhando na cena Ds e o mais legal de tudo é q vc ja tem uma base toda pronta inicializaçak leitura de roms isso tudo é magnifico e a imagem do seu emulador flui tao bem que me lembra o proprio Ds suave e linda a qualidade sei que vc vai obter grandes resultados com este magfico trabalho, como o amigo disse nois da comunidade vita somos muitos e pode ter certeza se vc se dedicar e precisar de ajuda financeira mta gente vai te ajudar basta abrir um patreon a gente temos ports hoje em dia inimaginaveis pro psvita tais como a franquia GTA, BULLYNG, DOOM3, E MTOS OUTROS JOGOS E EMULADORES LEMBRANDO QUE TEMOS TBM MTOS PORTS DE ANDROID, VC JA PENSOU SERA SE TRABALHASSE NO DESMUME DO ANDROID OU NO NOODS DO ANDROID PRO VITA NAO SERIA OBTIDO MELHORES RESULTADOS??

**Comment by vsmgammer** [comment]
So pra constar eu acompanho seu projeto todo dia e atualizo a pagina do gith umas 60 vezes por dia na esperanca de novidades pois sei que vc é capaz 👏👏👏 e sinto que isso nao ta longe meu canal é VSM GAMMER.

**Comment by Sal-gamer** [comment]
Vsm o Google tradutor vai comer seu texto kkkkk , ele e gringo tem muita abreviação no seu texto , mas também atualizo a página um monte de vez , é felizmente praticamente tem atualização todo dia 😁 vsm lembra de mim ? Sal game

**Comment by vsmgammer** [comment]
Claro sal meu brother

**Comment by Hydr8gon** [comment]
Closing this because it probably won't happen, sorry.

**Comment by Sal-gamer** [comment]
I just asked to run the Nintendo DS system on your emulator like adrenaline does, your emulator basically runs the Nintendo DS system, I changed several things in the configuration I opened several things like on the DS but it doesn't save, I would just like to run like on the DS , it doesn't seem so difficult to me, about the custom udcvudc plugin, I understand not doing it, it would take work to create a rendering of a second screen separately, and output this second screen to UDCD, on PS Vita, with the player being able to choose which screen goes to PS Vita and which screen goes to UDCD , but it doesn't mean that it's impossible, just laborious , a real shame, this project could have more PS Vita support, I really think that being able to freely access the DS menu save settings as on DS and not using a simple file explorer would be nice and a differentiator.
