### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by liandris** [Hydr8gon/NooDS#69]
Immediate error when running application.

```
---------------------------
Fatal Error
---------------------------
Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1016,wx containers,compatible with 2.8).
---------------------------
OK
---------------------------
```

Windows 8.1 here.

**Comment by NewJoarpa** [comment]
> 
> 
> Uhh, that's a new one. I assume you're using the release builds? If you're up for it, compiling a build yourself might fix the issue.

Same error here, compiled using MSYS2 and latest MinGW.
I'm currently on Windows 11.

I think this error is related to [wxWidgets issue #9909](https://github.com/msys2/MINGW-packages/issues/9909).

**Comment by Hydr8gon** [comment]
Oh, good to know. Hopefully it'll be fixed once the package is updated.

**Comment by NewJoarpa** [comment]
Confirmed to work in the new mingw-w64-x86_64-wxWidgets version "3.0.5.1-7".
There's no more ABI version mismatch error dialog.

**Comment by Hydr8gon** [comment]
Awesome, I'll close this then.
