### ISSUE TITLE
Homebrew: vFlip / hFlip attributes of sprites not handled correctly / differently from desmume

### ISSUE THREAD

**Issue by PH111P** [Hydr8gon/NooDS#74]
Hi, I tested https://github.com/neo-engine/neo on this emulator, and while everything is running very smoothly (including sound and saves, kudos for that!), this emulator somehow does not flip all sprites correctly:

![Screenshot_2022-01-14_21-44-39](https://user-images.githubusercontent.com/5598893/149518532-979801cb-f5b2-42f5-92dc-5443e116bc60.png)
For comparison: desmume (real hardware and melonDS yield the same result):
![Screenshot_2022-01-14_21-49-58](https://user-images.githubusercontent.com/5598893/149518614-8ec74e9c-76a5-4fb9-a5be-97cb8d70dfeb.png)

Another example (note that also the order of the sprites seems to be wrong):
![Screenshot_2022-01-14_21-48-08](https://user-images.githubusercontent.com/5598893/149518719-af12268d-2c15-4c94-9bff-517a52dfe9cc.png)
Desmume:
![Screenshot_2022-01-14_21-50-34](https://user-images.githubusercontent.com/5598893/149518742-0befd3b7-9dbf-4f2d-bb35-0bb8277de969.png)
 
 
 I reckon that this might be a problem related to libnds/devkitPro or the code of the aformentioned project, but nevertheless investigating might be worthwhile. 
 
 Edit: To add some more information: I built the emulator on (Arch) Linux from the most recent source code.

**Comment by Hydr8gon** [comment]
Oops, looks like I forgot to implement flipping for bitmap sprites. I'm surprised that hasn't been noticed sooner! Thanks for reporting, I'll have it fixed in a moment.
