### ISSUE TITLE
Classic NES Series: Super Mario Brothers (US/EU) doesn't boot up on Android Phone, just caused like this?

### ISSUE THREAD

**Issue by qamichele594-2** [Hydr8gon/NooDS#82]
The game gives this error message is "GAME PAK ERROR" on screen after GBA BIOS using FLASH Save type. The game works using EEPROM Save type.

### View for Screenshots here ;)
![Screenshot_20220131-035332](https://user-images.githubusercontent.com/98754754/151815863-1e3c3dc6-4eb6-4eaf-9b2d-b34ac57eded9.jpg)

**Comment by Hydr8gon** [comment]
This isn't a bug; classic NES games check the save type on boot, and fail if it isn't right. EEPROM and FLASH are very different, and the save type changer is only meant as a manual override if automatic detection fails.
