### ISSUE TITLE
[Pokemon Platinum] Hearthome City Gym Flashlight

### ISSUE THREAD

**Issue by EnchantedTorch** [Hydr8gon/NooDS#92]
The flashlight effect in Fantina's Gym affects the player, NPCs and the doormat but doesn't light up the ground in front correctly. Note that the flashlight does light up the floor, just extremely subtly. 
The effect isn't seen in Diamond and Pearl due to the Gym's gimmick not involving a flashlight.

https://youtu.be/dGlbC3f7w-w
(audio disabled due to both sources being recorded, sounds bad)

**Comment by Hydr8gon** [comment]
Looks like this is the same issue as #88, which I actually just fixed! The game uses transparent polygons to disable fog, which creates the effect of a light source. I wasn't properly updating the fog flag for transparent pixels, so that's what caused the issue.
