### ISSUE TITLE
Frontend support?

### ISSUE THREAD

**Issue by SoumyBhow** [Hydr8gon/NooDS#97]
Hello,

I'm currently trying out this emulator on an Android device and I was curious to know if it supports being launched from a frontend? If so, what is the launch activity and the file path parameter?

Thank you for your time.

**Comment by Hydr8gon** [comment]
Heh, I've been adding similar functionality for other platforms recently. I'm not sure how it works on Android, but I'll look into it.

**Comment by Hydr8gon** [comment]
This is now implemented with b29e06c. The activity is `com.hydra.noods.FileBrowser`, and the key is `LaunchPath`.

**Comment by SoumyBhow** [comment]
Yep just tried it and it works! Thanks so much!
